# Generated by Django 2.1.5 on 2019-02-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190204_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('dob', models.CharField(blank=True, max_length=12, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=75, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('state_province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
