# Generated by Django 2.1.5 on 2019-04-11 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190207_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date2',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
