# Generated by Django 2.1.5 on 2019-04-12 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20190410_1929'),
        ('books', '0009_book_publication_date2'),
    ]

    operations = [
    ]
