# Generated by Django 2.1.5 on 2019-04-05 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190330_1819'),
        ('addresses', '0002_auto_20190404_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='billing_profile',
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
