# Generated by Django 2.1.5 on 2019-04-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_auto_20190405_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
