# Generated by Django 2.1.5 on 2019-04-06 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'Amex'), ('discover', 'Discover')], max_length=120)),
                ('name_on_card', models.CharField(max_length=120)),
                ('card_number', models.CharField(max_length=120)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('ccv_code', models.CharField(max_length=4)),
                ('country', models.CharField(default='United States of America', max_length=120)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
