# Generated by Django 2.1.5 on 2019-04-06 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20190405_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
