# Generated by Django 2.1.5 on 2019-04-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20190405_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'verbose_name_plural': 'Cards'},
        ),
    ]
