# Generated by Django 2.1.5 on 2019-04-06 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0005_auto_20190405_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='profile',
        ),
        migrations.AddField(
            model_name='cards',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
